on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: node:15.0.1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm install
      - run: npm run esbuild
  test-job:
    runs-on: ubuntu-latest
    container: node:15.0.1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm install
      - run: npm run test
